### ISSUE TITLE
11월12일 idle_duration대신 몸의 비율로 실험

### ISSUE THREAD

**Issue by YimSungGoo** [YimSungGoo/daily#4]
0.15, 0.85로 변경, 0.20, 0.80도 동일
| File Name |  Rule Name |  True Positive |  False Positive |  False Negative |
|---|---|---|---|---|
| C032100_001.xml | PeopleCounting | 185 | 0 | **2** |
| C032300_002.xml | PeopleCounting | 116 | 0 | 0 |
| C119200_001.xml | PeopleCounting | 27 | 0 | **1** |
| C122300_003.xml | PeopleCounting | 25 | 0 | 0 |
| C125100_003.xml | PeopleCounting | 33 | 0 | 0 |
| TOTAL |  | 386 | 0 | **3** |

[PeopleCounting]"C032100_001.xml", TP: 185, FP: 0, FN: 2, Recall: 0.99, Precision: 1.00, F1-Score: 99.46
FN: "00:09:34", in_count: Some(96)
FN: "00:09:37", in_count: Some(98)

[PeopleCounting]"C032300_002.xml", TP: 116, FP: 0, FN: 0, Recall: 1.00, Precision: 1.00, F1-Score: 100.00

[PeopleCounting]"C119200_001.xml", TP: 27, FP: 0, FN: 1, Recall: 0.96, Precision: 1.00, F1-Score: 98.18
FN: "00:01:27", out_count: Some(5)

[PeopleCounting]"C122300_003.xml", TP: 25, FP: 0, FN: 0, Recall: 1.00, Precision: 1.00, F1-Score: 100.00

[PeopleCounting]"C125100_003.xml", TP: 33, FP: 0, FN: 0, Recall: 1.00, Precision: 1.00, F1-Score: 100.00

`C032100_001` 
7:43 정상적으로 egress
![image](https://github.com/user-attachments/assets/97114e96-da29-4538-8f57-5f0700eb5f34)

`C032300_002`
5:20 정상적으로 egress
![image](https://github.com/user-attachments/assets/2d7bc3c6-f22f-490e-b536-03998ccca9ce)

`C119200_001`
1:27 이벤트 발생안함
![image](https://github.com/user-attachments/assets/cd69d657-33f9-4497-a830-031d404c01d0)

1:56 정상적으로 egress
![image](https://github.com/user-attachments/assets/aab449c7-af53-4148-8a5e-6e3afcf46cf1)

`C125100_003`
1:13 정상적으로 다시 ingress track
![image](https://github.com/user-attachments/assets/70a4aef8-afd8-4a1c-96dd-eacee17f8002)

2:28 정상적으로 다시 ingress track
![image](https://github.com/user-attachments/assets/e4d34ca1-140c-4c2a-9f16-d9e7dfc6e25b)

**Comment by YimSungGoo** [comment]
```
[5/115] C001202_001.mp4 Intrusion 00:01:28.066 2644/13307                                                                                                                                       [h264 @ 0x618287ef5e40] corrupted macroblock 68 6 (total_coeff=-1)
[h264 @ 0x618287ef5e40] error while decoding MB 68 6
[5/115] C001202_001.mp4 Intrusion 00:01:28.133 2646/13307                                                                                                                                       [h264 @ 0x618288333280] Invalid NAL unit size (0 > 23858).
[h264 @ 0x618288333280] missing picture in access unit with size 23862
[h264 @ 0x6182883b7980] Invalid NAL unit size (0 > 23858).
[h264 @ 0x6182883b7980] Error splitting the input into NAL units.
[h264 @ 0x618288333280] Invalid NAL unit size (0 > 24125).
[h264 @ 0x618288333280] missing picture in access unit with size 24129
[h264 @ 0x6182843842c0] Invalid NAL unit size (0 > 24125).
[h264 @ 0x6182843842c0] Error splitting the input into NAL units.
[5/115] C001202_001.mp4 Intrusion 00:01:28.199 2648/13307                                                                                                                                       [h264 @ 0x618288333280] Invalid NAL unit size (0 > 21037).
[h264 @ 0x618288333280] missing picture in access unit with size 21041
[h264 @ 0x61828d9e93c0] Invalid NAL unit size (0 > 21037).
[h264 @ 0x61828d9e93c0] Error splitting the input into NAL units.
[h264 @ 0x618288333280] Invalid NAL unit size (0 > 27181).
[h264 @ 0x618288333280] missing picture in access unit with size 27185
[h264 @ 0x61828a6a6380] Invalid NAL unit size (0 > 27181).
[h264 @ 0x61828a6a6380] Error splitting the input into NAL units.

```
```
[1/1] C032100_001.mp4 PeopleCounting 00:05:44.266 10330/23012 PeopleCounting:eventing                                                                                                           
thread 'main' panicked at /home/yimstar9/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.27.0/src/algorithm/bool_ops/assembly.rs:45:13:
assembly segments must be eulierian
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: geo::algorithm::bool_ops::assembly::RegionAssembly<T>::finish
             at /home/yimstar9/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.27.0/src/algorithm/bool_ops/assembly.rs:45:13
   3: <geo::algorithm::bool_ops::spec::BoolOp<T> as geo::algorithm::bool_ops::spec::Spec<T>>::finish
             at /home/yimstar9/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.27.0/src/algorithm/bool_ops/spec.rs:52:9
   4: geo::algorithm::bool_ops::op::Proc<T,S>::sweep
             at /home/yimstar9/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.27.0/src/algorithm/bool_ops/op.rs:172:9
   5: <geo_types::geometry::polygon::Polygon<T> as geo::algorithm::bool_ops::BooleanOps>::boolean_op
             at /home/yimstar9/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.27.0/src/algorithm/bool_ops/mod.rs:69:9
   6: geo::algorithm::bool_ops::BooleanOps::intersection
             at /home/yimstar9/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.27.0/src/algorithm/bool_ops/mod.rs:30:9
   7: edn_types::zone::Zone::contains_almost
             at ./edn-types/src/zone.rs:49:32
   8: <edn_rules::rules::people_counting::PeopleCountingInside as edn_rules::zone_track::ZoneTrackerInside<T>>::inside
             at ./edn-rules/src/rules/people_counting.rs:247:13
   9: edn_rules::zone_track::ZoneTracker<T,I>::feed
             at ./edn-rules/src/zone_track.rs:207:26
  10: <edn_rules::rules::people_counting::PeopleCountingRule as edn_rules::rule::Rule>::check
             at ./edn-rules/src/rules/people_counting.rs:144:24
  11: edn_rules::executor::RuleExecutor::check
             at ./edn-rules/src/executor.rs:188:39
  12: edn_kisa::process
             at ./edn-kisa/src/main.rs:290:23
  13: edn_kisa::main
             at ./edn-kisa/src/main.rs:128:9
  14: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
[41/115] C014202_001.mp4 Intrusion 00:07:16.731 13104/14227                                                                                                                                     
[1]    18287 segmentation fault (core dumped)  cargo run -p edn-kisa -- /media/qnap/yimstar9/KISA/data/all -o  -O  -s

```

**Comment by YimSungGoo** [comment]
```
[1/1] C032100_001.mp4 PeopleCounting 00:05:44.266 10330/23012 PeopleCounting:eventing                                                                                                           
thread 'main' panicked at /home/yimstar9/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.27.0/src/algorithm/bool_ops/assembly.rs:45:13:
assembly segments must be eulierian
```
이 에러는 cpu로 연산시 정밀도 때문에 발생함.
소수점 넷째자리까지만 표시하도록 반올림하면 에러없이 잘됨.
